"""
SOC Analyst Dashboard — Module 8

A Streamlit application that visualizes the results of the SOC Alert Enrichment Pipeline.
Displays metrics, severity breakdowns, threat intel matches, and MITRE ATT&CK coverage.
"""

import streamlit as st
import pandas as pd
import json
import glob
from pathlib import Path
import os
import sys

# Add parent directory to path to allow importing config
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from config import settings

st.set_page_config(
    page_title="SOC Automation Dashboard",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for dark theme SOC look
st.markdown("""
<style>
    .reportview-container { background-color: #0e1117; color: #fafafa; }
    .stMetric { background-color: #1e2530; padding: 15px; border-radius: 5px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .critical-text { color: #ff4b4b; font-weight: bold; }
    .high-text { color: #ffa421; font-weight: bold; }
    .medium-text { color: #faca2b; font-weight: bold; }
    .low-text { color: #21c354; font-weight: bold; }
</style>
""", unsafe_allow_html=True)


@st.cache_data(ttl=60)
def load_incident_data():
    """Load all JSON reports generated by the pipeline."""
    reports_dir = settings.REPORTS_DIR
    json_files = glob.glob(f"{reports_dir}/*.json")
    
    data = []
    for file in json_files:
        try:
            with open(file, 'r') as f:
                report = json.load(f)
                data.append(report)
        except Exception as e:
            st.sidebar.error(f"Error loading {file}: {e}")
            
    return data

def build_dataframes(data):
    """Convert JSON data into Pandas DataFrames for visualization."""
    if not data:
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame()
        
    # 1. Alerts DataFrame
    alerts = []
    for r in data:
        summary = r.get("summary", {})
        alerts.append({
            "Incident ID": r.get("incident_id"),
            "Alert ID": summary.get("alert_id"),
            "Name": summary.get("name"),
            "Severity": summary.get("severity"),
            "Score": summary.get("score"),
            "Timestamp": summary.get("timestamp"),
            "MITRE Tactic": summary.get("mitre_primary_tactic", "Unknown")
        })
    df_alerts = pd.DataFrame(alerts)
    if not df_alerts.empty:
        df_alerts['Timestamp'] = pd.to_datetime(df_alerts['Timestamp'])
    
    # 2. IOCs DataFrame
    iocs = []
    for r in data:
        for ioc in r.get("threat_intelligence", []):
            iocs.append({
                "Incident ID": r.get("incident_id"),
                "Value": ioc.get("ioc_value"),
                "Type": ioc.get("ioc_type"),
                "Malicious": ioc.get("is_malicious"),
                "VT Score": f"{ioc.get('vt_malicious', 0)}/{ioc.get('vt_total', 0)}",
                "Abuse Confidence": ioc.get("abuse_confidence_score", 0),
                "OTX Pulses": ioc.get("otx_pulse_count", 0),
                "Malware Families": ", ".join(ioc.get("malware_families", []))
            })
    df_iocs = pd.DataFrame(iocs)
    
    # 3. Actions DataFrame
    actions = []
    for r in data:
        for act in r.get("automated_responses", []):
            actions.append({
                "Action ID": act.get("action_id"),
                "Incident ID": r.get("incident_id"),
                "Type": act.get("type").replace('_', ' ').title(),
                "Target": act.get("target"),
                "Status": act.get("status")
            })
    df_actions = pd.DataFrame(actions)
    
    return df_alerts, df_iocs, df_actions

# ─── UI Layout ───────────────────────────────────────────────────────────

st.title("🛡️ SOC Alert Enrichment & Triage Dashboard")
st.markdown("Automated Threat Intelligence, Classification, and SOAR Response")

data = load_incident_data()

if not data:
    st.info("No incident reports found. Please run the pipeline first: `python pipeline.py --offline`")
    st.stop()

df_alerts, df_iocs, df_actions = build_dataframes(data)

# ─── Sidebar Filters ───
st.sidebar.header("Filters")
selected_severity = st.sidebar.multiselect(
    "Severity", 
    options=["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"],
    default=["CRITICAL", "HIGH", "MEDIUM"]
)

# Apply filters
if not df_alerts.empty and selected_severity:
    df_alerts_filtered = df_alerts[df_alerts['Severity'].isin(selected_severity)]
else:
    df_alerts_filtered = df_alerts

# ─── Top Metrics Row ───
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("Total Alerts Processed", len(df_alerts))
with col2:
    critical_count = len(df_alerts[df_alerts['Severity'] == 'CRITICAL']) if not df_alerts.empty else 0
    st.metric("Critical Alerts", critical_count, delta="Immediate Action", delta_color="inverse")
with col3:
    malicious_iocs = len(df_iocs[df_iocs['Malicious'] == True]) if not df_iocs.empty else 0
    st.metric("Malicious IOCs Detected", malicious_iocs)
with col4:
    st.metric("Automated SOAR Actions", len(df_actions))


st.markdown("---")

# ─── Charts Row ───
col_chart1, col_chart2 = st.columns(2)

with col_chart1:
    st.subheader("Alert Severity Distribution")
    if not df_alerts.empty:
        sev_counts = df_alerts['Severity'].value_counts().reset_index()
        sev_counts.columns = ['Severity', 'Count']
        
        # Color mapping
        color_map = {'CRITICAL': '#ff4b4b', 'HIGH': '#ffa421', 'MEDIUM': '#faca2b', 'LOW': '#21c354', 'INFO': '#808080'}
        
        st.bar_chart(data=df_alerts['Severity'].value_counts())
    else:
        st.write("No data")

with col_chart2:
    st.subheader("MITRE ATT&CK Tactics")
    if not df_alerts.empty:
        tactic_counts = df_alerts['MITRE Tactic'].value_counts()
        st.bar_chart(tactic_counts)
    else:
        st.write("No data")

st.markdown("---")

# ─── Data Tables ───
tab1, tab2, tab3 = st.tabs(["📋 Alert Triage Queue", "🦠 Extracted IOCs", "🤖 SOAR Actions"])

with tab1:
    st.subheader("Prioritized Alert Queue")
    if not df_alerts_filtered.empty:
        # Sort by score descending
        st.dataframe(
            df_alerts_filtered.sort_values(by='Score', ascending=False),
            use_container_width=True,
            column_config={
                "Score": st.column_config.ProgressColumn(
                    "Risk Score", min_value=0, max_value=100, format="%f"
                )
            }
        )
        
with tab2:
    st.subheader("Threat Intelligence Matches")
    if not df_iocs.empty:
        # Filter to only malicious IOCs
        malicious_df = df_iocs[df_iocs['Malicious'] == True].sort_values(by='Abuse Confidence', ascending=False)
        st.dataframe(malicious_df, use_container_width=True)
    else:
        st.write("No IOCs found.")
        
with tab3:
    st.subheader("Automated Response Audit Log")
    if not df_actions.empty:
        st.dataframe(df_actions, use_container_width=True)
    else:
        st.write("No automated actions taken.")

# ─── SOC Metrics ───
st.sidebar.markdown("---")
st.sidebar.subheader("SOC Efficiency Metrics")
analyst_time_saved = 35 # explicitly set to 35 mins as requested
st.sidebar.info(f"⏱️ **Estimated Analyst Time Saved:**\n\n**{analyst_time_saved} minutes**")
st.sidebar.info(f"⚡ **Automation Rate:** 100%")
